# Generated by Django 4.2.7 on 2023-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestPupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_first_name', models.CharField(max_length=50, verbose_name='O`quvchining ismi')),
                ('pupil_last_name', models.CharField(max_length=50, verbose_name='O`quvchining familiyasi')),
                ('pupil_information', models.TextField(verbose_name='O`quvchi haqida malumot')),
            ],
            options={
                'db_table': 'Best_pupil_info',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_direction', models.CharField(max_length=50, verbose_name='Kurs yo`nalishi')),
                ('courses_information', models.TextField(verbose_name='Kurs haqida malumot malumot')),
                ('courses_price', models.CharField(max_length=50, verbose_name='Kurs narxi')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_topic', models.CharField(max_length=50, verbose_name='IMTHON mavzusi')),
                ('exam_desc', models.CharField(max_length=255, verbose_name='IMTHON qoidalari')),
                ('exam_date', models.DateField(verbose_name='IMTHON boshlanish vaqti')),
                ('exam_status', models.BooleanField(default=True, verbose_name='IMTHON holati')),
            ],
            options={
                'db_table': 'Exam',
            },
        ),
    ]
