# Generated by Django 4.2.7 on 2023-12-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_first_name', models.CharField(max_length=50, verbose_name='Teacher name')),
                ('teach_last_name', models.CharField(max_length=50, verbose_name='Teacher last')),
                ('teach_specialist', models.CharField(max_length=50, verbose_name='mutahasisligi')),
                ('teach_informations', models.TextField(verbose_name='O`qituvchi haqida malumot')),
            ],
            options={
                'db_table': 'teachers_info',
            },
        ),
        migrations.CreateModel(
            name='TradeUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_union_name', models.CharField(max_length=100, verbose_name='Kasaba uyishmasi nomi')),
                ('trade_union_leader', models.CharField(max_length=50, verbose_name='Kasaba uyishmasi rahbari')),
                ('trade_union_desc', models.CharField(max_length=255, verbose_name='Kasaba uyishmasi haqida qisqacha')),
                ('trade_union_staff', models.ManyToManyField(to='app_teachers.staff')),
            ],
            options={
                'db_table': 'trade_union',
            },
        ),
        migrations.CreateModel(
            name='LessonDevelopments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_topic', models.CharField(max_length=50, verbose_name='Dars mavzusi')),
                ('lesson_desc', models.CharField(max_length=255, verbose_name='Dars haqida qisqacha')),
                ('lesson_date', models.DateTimeField(auto_now_add=True, verbose_name='Darsnig boshlanish vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_teachers.category')),
            ],
        ),
    ]
