# Generated by Django 4.2.7 on 2023-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title_uz', models.CharField(max_length=300, verbose_name='Yangiliklar sarlavhasi')),
                ('news_title_ru', models.CharField(max_length=300, verbose_name='заголовок новости')),
                ('news_title_en', models.CharField(max_length=300, verbose_name='News title')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='image/news', verbose_name='Image')),
                ('news_desc_uz', models.CharField(max_length=500, verbose_name='Yangiliklar qisqacha tavsifi')),
                ('news_desc_ru', models.CharField(max_length=500, verbose_name='описание новости')),
                ('news_desc_en', models.CharField(max_length=500, verbose_name='News description')),
                ('news_text_uz', models.TextField(verbose_name="Yangiliklar to'liq tavsifi")),
                ('news_text_ru', models.TextField(verbose_name='Tekct новости')),
                ('news_text_en', models.TextField(verbose_name='News text')),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_views_count', models.IntegerField(default=0, verbose_name='Ko`rishlar soni')),
                ('news_source', models.URLField(verbose_name='Manba (agar mavjud bo`lsa)')),
            ],
        ),
    ]
