# Generated by Django 4.2.7 on 2023-12-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_source',
            field=models.URLField(blank=True, null=True, verbose_name='Manba (agar mavjud bo`lsa)'),
        ),
    ]
