# Generated by Django 4.2.7 on 2023-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0003_alter_news_news_title_en_alter_news_news_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons_title_uz', models.CharField(max_length=300, verbose_name="E'lon sarlavhasi")),
                ('anons_title_ru', models.CharField(max_length=300, verbose_name='заголовок obyavleniyae')),
                ('anons_title_en', models.CharField(max_length=300, verbose_name='Announcement title')),
                ('anons_desc_uz', models.CharField(max_length=500, verbose_name="E'lon qisqacha tavsifi")),
                ('anons_desc_ru', models.CharField(max_length=500, verbose_name='описание obyavleniyae')),
                ('news_desc_en', models.CharField(max_length=500, verbose_name='Announcement description')),
                ('anons_datetime', models.DateTimeField(auto_now_add=True)),
                ('anons_dateline', models.DateTimeField()),
            ],
        ),
    ]
