# Generated by Django 4.2.7 on 2023-12-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title_uz', models.CharField(max_length=255, verbose_name='Hujjatlar nomi')),
                ('doc_title_ru', models.CharField(max_length=255, verbose_name='название документа')),
                ('doc_title_en', models.CharField(max_length=255, verbose_name='Documents name')),
                ('doc_type', models.CharField(choices=[('4', 'Buyruq'), ('1', 'Qonun'), ('5', 'Farmon'), ('3', 'Farmoish'), ('2', 'Qaror')], max_length=15, verbose_name='Toifasi/type')),
                ('org_type', models.CharField(choices=[('5', 'Boshqarma'), ('2', 'Prezident'), ('4', 'Xalq talim vazirligi'), ('3', 'Vazirlar mahkamasi'), ('1', 'Parlamen')], max_length=25, verbose_name='Tashkilot/Organisation')),
                ('doc_code', models.CharField(max_length=50, verbose_name='N˚')),
                ('doc_date', models.DateField(verbose_name='Hujjat qabul qilingan vaqt')),
                ('doc_link', models.URLField(blank=True, null=True, verbose_name='Hujjat havolasi')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
    ]
