# Generated by Django 4.2.7 on 2023-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0003_internaldocs_alter_documents_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(choices=[('4', 'Buyruq'), ('1', 'Qonun'), ('3', 'Farmoish'), ('5', 'Farmon'), ('2', 'Qaror')], max_length=15, verbose_name='Toifasi/type'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='org_type',
            field=models.CharField(choices=[('3', 'Vazirlar mahkamasi'), ('1', 'Parlamen'), ('4', 'Xalq talim vazirligi'), ('2', 'Prezident'), ('5', 'Boshqarma')], max_length=25, verbose_name='Tashkilot/Organisation'),
        ),
        migrations.AlterField(
            model_name='internaldocs',
            name='doc_type',
            field=models.CharField(choices=[('2', 'Buyruq'), ('1', 'Qaror')], max_length=15, verbose_name='Toifasi/type'),
        ),
    ]
