# Generated by Django 4.2.7 on 2023-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0009_alter_documents_doc_type_alter_documents_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(choices=[('4', 'Buyruq'), ('5', 'Farmon'), ('3', 'Farmoish'), ('1', 'Qonun'), ('2', 'Qaror')], max_length=15, verbose_name='Toifasi/type'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='org_type',
            field=models.CharField(choices=[('2', 'Prezident'), ('5', 'Boshqarma'), ('3', 'Vazirlar mahkamasi'), ('1', 'Parlamen'), ('4', 'Xalq talim vazirligi')], max_length=25, verbose_name='Tashkilot/Organisation'),
        ),
        migrations.AlterField(
            model_name='internaldocs',
            name='doc_type',
            field=models.CharField(choices=[('1', 'Qaror'), ('2', 'Buyruq')], max_length=15, verbose_name='Toifasi/type'),
        ),
    ]
